spring.application.name=uniform
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/uniform_db
spring.datasource.username=root
spring.datasource.password=root123

server.servlet.session.timeout = 7200

spring.servlet.multipart.enabled=true
# ファイル1つの最大サイズ
spring.servlet.multipart.max-file-size=10MB
# 複数ファイル全体の最大サイズ
spring.servlet.multipart.max-request-size=50MB

#メール用
## サーバーを指定（xserver の SMTP サーバーを利用）
#spring.mail.host = sv5215.xserver.jp
## ポート番号
#spring.mail.port = 587
## サーバーにログインするメールアドレス（またはユーザー名）
#spring.mail.username = test.sender@kanda-it-school-system.com
## サーバーにログインするパスワード
#spring.mail.password = kandaSender-2025
## SMTP認証を有効にする設定
#spring.mail.properties.mail.smtp.auth = true
## STARTTLSを有効にする設定
#spring.mail.properties.mail.smtp.starttls.enable = true

# サーバーを指定（xserver の SMTP サーバーを利用）
#spring.mail.host = sv5215.xserver.jp
## ポート番号
#spring.mail.port = 587
## サーバーにログインするメールアドレス（またはユーザー名）
#spring.mail.username = system.project.team15@kanda-it-school-system.com
## サーバーにログインするパスワード
#spring.mail.password = i1jkv4dR4Z8m0bA
## SMTP認証を有効にする設定
#spring.mail.properties.mail.smtp.auth = true
## STARTTLSを有効にする設定
#spring.mail.properties.mail.smtp.starttls.enable = true

# サーバーを指定（xserver の SMTP サーバーを利用）
spring.mail.host = sv5215.xserver.jp

# ポート番号
spring.mail.port = 587

# サーバーにログインするメールアドレス（またはユーザー名）
spring.mail.username = test.sender@kanda-it-school-system.com
# サーバーにログインするパスワード
spring.mail.password = kandaSender-2026
# SMTP認証を有効にする設定
spring.mail.properties.mail.smtp.auth = true

# STARTTLSを有効にする設定
spring.mail.properties.mail.smtp.starttls.enable = true